services:
  debian:
    image: localhost/debian-lab-snapshot:latest
    container_name: debian-lab
    restart: "no"
    stdin_open: true
    tty: true
    cap_add:
      - NET_RAW
    ports:
      - "2222:22"
    working_dir: /root
    volumes:
      - debian-state:/root
      - ./workspace:/root/workspace
      - ./workspace/.config/starship.toml:/root/.config/starship.toml:ro
      - ./workspace/.config/config.jsonc:/root/.config/fastfetch/config.jsonc:ro

volumes:
  debian-state:
