services:
  debian:
    build: .
    container_name: debian-lab
    restart: "no"
    stdin_open: true
    tty: true
    working_dir: /root
    volumes:
      - debian-state:/root
      - ./workspace:/root/workspace
      - ./workspace/.config/starship.toml:/root/.config/starship.toml:ro
      - ./workspace/.config/config.jsonc:/root/.config/fastfetch/config.jsonc:ro

volumes:
  debian-state:
